### ISSUE TITLE
Missing output from train.sh

### ISSUE THREAD

**Issue by wilke** [JDACS4C-IMPROVE/SWnet#12]
using definition file from Singularity repo, running the train script produces no output:
```
        git clone https://github.com/gihanpanapitiya/SWnet.git
        cd SWnet
        git checkout develop
```

```
~/release/Singularity$ singularity run --nv --bind `pwd`/tmp:/candle_data_dir build/SWnet.sif train.sh 5 /candle_data_dir --epochs 1
(IMPROVE) wilke@lambda7:~/release/Singularity$
```

_Originally posted by @wilke in https://github.com/JDACS4C-IMPROVE/SWnet/issues/6#issuecomment-1741113667_

**Comment by gihanpanapitiya** [comment]
@wilke Can you merge my most recent pull request? line 36 of the definition file has to be changed as,
git checkout develop.

**Comment by wilke** [comment]
I am closing this issue and restarting testing and integration from scratch for the next release.
